apiVersion: exphost.pl/v1
kind: Password
metadata:
  name: password-mail-redmine
spec:
  name: password-mail-redmine
  types:
    - sha512
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-ldap-mail-redmine
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: ldap
        image: bitnami/openldap:2.5
        command:
          - /bin/bash
          - -c
          - 'echo -e "
dn: maildrop=redmine@{{ .Values.domain }},ou=mails,{{ include "ldap.dc" . }}\n
changetype: add\n
maildrop: redmine@{{ .Values.domain }}\n
objectClass: person\n
objectClass: postfixUser\n
objectClass: top\n
cn: redmine\n
sn: mail\n
mailacceptinggeneralid: redmine@{{ .Values.domain }}\n
userPassword:: $(echo -n {crypt}$PASSWORD|base64 -w0)
"|sed -e "s/^ //" >/tmp/ldif.ldif
            ;
            echo "qweqwe";
            cat /tmp/ldif.ldif;
            ldapmodify -a -x -H ldap://openldap -D cn=admin,{{ include "ldap.dc" . }} -w $ADMINPASSWORD -f /tmp/ldif.ldif;
            echo $?
            '
        env:
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: password-password-mail-redmine-from-tenant-exphost-services
                key: sha512
          - name: ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: password-password-ldap-admin-from-tenant-exphost-services
                key: password
