---
include:
  - https://gitlab.exphost.pl/exphost/exphost-helms/-/raw/master/common/gitlab-ci.yml

stages:
  - checks
  - upload
  - deploy

upload:
  extends: .upload

deploy-to-dev:
  stage: deploy
  image: alpine
  extends: .deploy-to-git-mainapp
  environment:
    name: dev
  variables:
    repo: git@gitlab.exphost.pl:exphost/tenant-exphost-services-home-lab.git
    yamlfile: exphost-services.yml
    waitapp: tenant-exphost-services-exphost-services
    refreshapp: tenant-exphost-services
