---
include:
  - https://gitlab.exphost.pl/exphost/exphost-helms/-/raw/master/common/gitlab-ci.yml
  - https://gitlab.exphost.pl/exphost/exphost-helms/-/raw/master/common/git.yml

stages:
  - checks
  - upload
  - deploy

deploy-to-dev:
  stage: deploy
  image: alpine
  extends: .deploy-to-git
  environment:
    name: dev
  variables:
    repo: git@gitlab.exphost.pl:exphost/tenant-exphost-services-home-lab.git
    patch_cmd: 'yq e -i ".spec.source.targetRevision=\"$$VERSION\"" exphost-services.yml'
