apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - kopf.zalando.org/KopfFinalizerMarker
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: tenant-exphost-services
  source:
    repoURL: 'https://charts.gitlab.io/'
    targetRevision: 5.10.2
    chart: gitlab
    helm:
      values: |
        certmanager:
          installCRDs: false
          install: false
        prometheus:
          install: false
        certmanager-issuer:
          email: gitlab_certmanager@fabrykowski.pl
        global:
          hosts:
            domain: gitlab.{{ .Values.domain }}
            gitlab:
              name: gitlab.{{ .Values.domain }}
          ingress:
            class: nginx
            configureCertmanager: false
            annotations:
              "cert-manager.io/cluster-issuer": acme-issuer
          appConfig:
            omniauth:
              enabled: true
              allowSingleSignOn: true
              autoLinkUser: true
              providers:
                - secret: gitlab-providers-dex
                  key: provider
            incomingEmail:
              enabled: true
              address: gitlab@{{ .Values.domain }}
              host: imap.{{ .Values.domain }}
              port: 143
              ssl: false
              startTls: true
              user: gitlab@{{ .Values.domain }}
              password:
                secret: password-password-mail-gitlab-from-tenant-exphost-services
                key: password
              
          smtp:
            enabled: true
            address: smtp.{{ .Values.domain }}
            port: 587
            user_name: gitlab@{{ .Values.domain }}
            password:
              secret: password-password-mail-gitlab-from-tenant-exphost-services
              key: password
            starttls_auto: true
            authentication: "login"
          email:
            from: gitlab@{{ .Values.domain }}
          pages:
            enabled: True
            host: pages.gitlab.dev.exphost.pl

        gitlab:
          webservice:
            ingress:
              tls:
                secretName: moj-gitlab-tls
          gitaly:
            persistence:
              size: {{ .Values.gitlab.gitaly.persistence.size }}
{{- if .Values.gitlab.gitaly.persistence.storageClass }}
              storageClass: {{ .Values.gitlab.gitaly.persistence.storageClass }}
{{- end }}
          gitlab-shell:
            service:
              type: LoadBalancer
              annotations:
                metallb.universe.tf/allow-shared-ip: ingress-ip
        registry:
          ingress:
            tls:
              secretName: moj-registry-tls
        minio:
          ingress:
            tls:
              secretName: moj-minio-tls
          persistence:
            size: {{ .Values.gitlab.minio.persistence.size }}
{{- if .Values.gitlab.minio.persistence.storageClass }}
            storageClass: {{ .Values.gitlab.minio.persistence.storageClass }}
{{- end }}
        gitlab-runner:
          runners:
            config: |
              [[runners]]
                [runners.kubernetes]
                  image = "ubuntu:20.04"
                  privileged = true
        #gitlab-runner:
        #  runners:
        #    config: |
        #      [[runners]]
        #        [runners.kubernetes]
        #        image = "ubuntu:18.04"
        #        helper_image = "registry.gitlab.com/gitlab-org/ci-cd/gitlab-runner-ubi-images/gitlab-runner-helper:x86_64-fcbb560f"

        nginx-ingress:
          enabled: false
        postgresql:
          persistence:
            size: {{ .Values.gitlab.postgresql.persistence.size }}
{{- if .Values.gitlab.postgresql.persistence.storageClass }}
            storageClass: {{ .Values.gitlab.postgresql.persistence.storageClass }}
{{- end }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tenant-exphost-services
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
