apiVersion: exphost.pl/v1
kind: Template
metadata:
  finalizers:
  - kopf.zalando.org/KopfFinalizerMarker
  name: redmine-mail-password
spec:
  destination_name: redmine-mail-password
  destination_type: Secret
  templates:
    REDMINE_SMTP_PASSWORD: |
      {{ "{{" }} mail_password {{ "}}" }}
    REDMINE_SMTP_AUTH: login
  values:
    - name: mail_password
      source_name: password-password-mail-redmine-from-tenant-exphost-services
      source_type: Secret
      source_key: password

