apiVersion: exphost.pl/v1
kind: Template
metadata:
  finalizers:
  - kopf.zalando.org/KopfFinalizerMarker
  name: redmine-password
spec:
  destination_name: redmine-secrets
  destination_type: Secret
  templates:
    redmine-password: |
      {{ "{{" }} redmine_password {{ "}}" }}
    mariadb-password: |
      {{ "{{" }} mariadb_password {{ "}}" }}
    mariadb-root-password: |
      {{ "{{" }} mariadb_root_password {{ "}}" }}
  values:
    - name: redmine_password
      source_name: password-redmine-password-from-tenant-exphost-services
      source_type: Secret
      source_key: password
    - name: mariadb_password
      source_name: password-mariadb-password-from-tenant-exphost-services
      source_type: Secret
      source_key: password
    - name: mariadb_root_password
      source_name: password-mariadb-root-password-from-tenant-exphost-services
      source_type: Secret
      source_key: password
