apiVersion: exphost.pl/v1
kind: Template
metadata:
  finalizers:
  - kopf.zalando.org/KopfFinalizerMarker
  name: redmine-password
spec:
  destination_key: redmine-password
  destination_name: redmine-secrets
  destination_type: Secret
  template: |
    {{ "{{" }} password {{ "}}" }}
  values:
    - name: password
      source_name: password-redmine-password-from-tenant-exphost-services
      source_type: Secret
      source_key: password
---
apiVersion: exphost.pl/v1
kind: Template
metadata:
  finalizers:
  - kopf.zalando.org/KopfFinalizerMarker
  name: mariadb-password
spec:
  destination_key: mariadb-password
  destination_name: redmine-secrets
  destination_type: Secret
  template: |
    {{ "{{" }} password {{ "}}" }}
  values:
    - name: password
      source_name: password-mariadb-password-from-tenant-exphost-services
      source_type: Secret
      source_key: password
---
apiVersion: exphost.pl/v1
kind: Template
metadata:
  finalizers:
  - kopf.zalando.org/KopfFinalizerMarker
  name: mariadb-root-password
spec:
  destination_key: mariadb-root-password
  destination_name: redmine-secrets
  destination_type: Secret
  template: |
    {{ "{{" }} password {{ "}}" }}
  values:
    - name: password
      source_name: password-mariadb-root-password-from-tenant-exphost-services
      source_type: Secret
      source_key: password

