apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redmine
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    - kopf.zalando.org/KopfFinalizerMarker
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: tenant-exphost-services
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 18.0.2
    chart: redmine
    helm:
      values: |
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostname: redmine.{{ .Values.domain }}
          annotations:
            cert-manager.io/cluster-issuer: acme-issuer
          tls: true
        postgresql:
          enabled: false
        redmineUsername: admin
        existingSecret: redmine-secrets
        mariadb:
          auth:
            existingSecret: redmine-secrets
          existingSecret: redmine-secrets
          persistence:
            size: {{ .Values.redmine.persistence.size }}
{{- if .Values.redmine.persistence.storageClass }}
            storageClass: {{ .Values.redmine.persistence.storageClass }}
{{- end }}
        redmineEmail: redmine@{{ .Values.domain }}
        smtpHost: smtp.{{ .Values.domain }}
        smtpPort: 587
        smtpUser: redmine@{{ .Values.domain }}
        smtpProtocol: "tls"
        extraEnvVarsSecret: redmine-mail-password
        initContainers:
          - name: generate-ssh-key
            image: alpine
            command: ['sh', '-c', 'apk add openssh-keygen; [ -e /repos/key ] && echo "key exists" || ssh-keygen -N "" -t rsa -f /repos/key && cat /repos/key.pub']
            volumeMounts:
              - mountPath: /repos
                name: redmine-repos
          - name: theme-farend-blueclair
            image: alpine
            command: ['sh', '-c', 'apk add git; git clone -b redmine4.2  https://github.com/farend/redmine_theme_farend_bleuclair.git /themes/']
            volumeMounts:
              - mountPath: /themes
                name: theme-farend-blueclair
        sidecars:
          - name: git-updater
            image: alpine
            command:
              - sh
              - -c
              - "apk add jq yq git openssh-client curl;
                cd /repos;
                export GIT_SSH_COMMAND='ssh -i /repos/key -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null';
                while true; do
                  cat /configmaps/repos;
                  yq e -o=json  /configmaps/repos |jq -r '.[] | [.name, .repo] | @tsv' > /tmp/repos.txt;
                  while IFS=$'\t' read -r name repo _; do
                    echo processing \"$repo\" \"$name\";
                    [ -d $name ] && (echo 'found. updating'; cd \"$name\"; git fetch origin master:master)||(echo 'not found. clonning'; git clone --bare \"$repo\" \"$name\")
                  done </tmp/repos.txt;
                  [ -e /configmaps/ws ] && (echo 'triggering refresh'; curl -s localhost:3000/sys/fetch_changesets?key=$(cat /configmaps/ws));
                  sleep 60;
                done"
            volumeMounts:
              - mountPath: /repos
                name: redmine-repos
              - mountPath: /configmaps
                name: repo-configs
        extraVolumes:
          - name: repo-configs
            configMap:
              name: redmine-repos-configs
          - name: redmine-repos
            persistentVolumeClaim:
              claimName: redmine-repos
          - name: theme-farend-blueclair
            emptyDir: {}
        extraVolumeMounts:
          - mountPath: /repos
            name: redmine-repos
          - mountPath: /opt/bitnami/redmine/public/themes/theme-farend-blueclair
            name: theme-farend-blueclair
        persistence:
          size: {{ .Values.redmine.persistence.size }}
{{- if .Values.redmine.persistence.storageClass }}
          storageClass: {{ .Values.redmine.persistence.storageClass }}
{{- end }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tenant-exphost-services
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
