apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-repos
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  volumeMode: Filesystem
